### ISSUE TITLE
error generating man

### ISSUE THREAD

**Issue by dpinol** [cmosetick/docker-manpages-osx#1]
I have macOs 10.12.3 with docker 1.13

thanks

`[INFO]	--> Setting version for golang.org/x/sys to 62bee037599929a6e9146f29d10dd5208c43507d.
 ---> e08a3d19f389
Removing intermediate container 93ca91c69c85
Step 10/13 : ENV GOPATH $GOPATH:/manvendor
 ---> Running in ea0ecb651afb
 ---> 495bd5ec12ed
Removing intermediate container ea0ecb651afb
Step 11/13 : RUN go build -o /usr/bin/go-md2man github.com/cpuguy83/go-md2man
 ---> Running in caeeabfafc67
 ---> 931a04df2673
Removing intermediate container caeeabfafc67
Step 12/13 : WORKDIR /go/src/github.com/docker/docker/
 ---> b7954c2591e4
Removing intermediate container 819cbb858707
Step 13/13 : ENTRYPOINT man/generate.sh
 ---> Running in 7215bfc902d0
 ---> e663bea3d6e4
Removing intermediate container 7215bfc902d0
Successfully built e663bea3d6e4
container_linux.go:247: starting container process caused "exec: \"man/generate.sh\": stat man/generate.sh: no such file or directory"
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"man/generate.sh\": stat man/generate.sh: no such file or directory".
cp: cannot stat 'man*': No such file or directory
No manual entry for docker`

**Comment by cmosetick** [comment]
Hi @dpinol There were issues with the upstream components that my script referenced. I have updated the script and associated files, and it should work correctly for you now.

Please pull down the latest version of `docker-man-pages-osx.sh` and let me know your results.
Thank you,
Chris

**Comment by dpinol** [comment]
thanks, it works great now
