### ISSUE TITLE
:( man directory no longer exists in the docker git

### ISSUE THREAD

**Issue by knope** [cmosetick/docker-manpages-osx#2]
the following in your executable will cause failure currently:
```bash
git clone https://github.com/docker/docker.git
cd docker/man
```

it looks like the `./man` directory is moved into the related docs branch, at time of writing this see `docs-v1.12.1-2016-08-12`

**Comment by cmosetick** [comment]
I updated the script in August to point to docker-ce repository, as that is where the man directory seems to be now.
i.e. `cd docker-ce/components/cli/man`

The amount of generated man pages is way less than before now. :-(
Regardless, let me know if the updated version of the script is working now!
